export const LANG_EN_TRANS = {
    'home': 'Home',
    'login': 'Log In',
    'thailand_post_full_name': 'Thailand Post Company Limited',
    'search_for_products': 'Search for products...',
    'search_results_for': 'Search results for',
    'all': 'All',

    'product_category': 'CATEGORIES',
    'new_products': 'NEW PRODUCTS',
    'best_seller': 'BEST SELLER',

    'sub_category': 'SUB CATEGORIES',

    'results_for': 'Results for',
    'no_result': 'No result',
    'related_category': 'Related Categories',
    'items': 'item(s)',

    'login_to': 'Log In to',
    'full_name': 'Name',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'not_a_member': 'Not a Member?',
    'sign_up_now': 'Sign up Now',
    'create_account': 'Create Account',
    'create_a_new_account': 'Create a New Account',

    'description': 'Description',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',

    'cart': 'Cart',
    'delivery_address': 'Delivery Address',
    'payment': 'Payment',
    'payment_option': 'Payment Option',
    'complete': 'Complete',
    'product': 'Product',
    'price': 'Price',
    'quantity': 'Qty',
    'qty': 'Qty',
    'total': 'Total',
    'total_summary': 'Total Summary',
    'select_address': 'Select Address',
    'choose_payment_option': 'Choose Payment Option',
    'order_summary': 'Order Summary',
    'place_order': 'Place Order',
    'order_no': 'Order No',
    'order_detail': 'Order Detail',
    'order_date': 'Date',
    'order_status': 'Status',
    'order_short_info': 'Summary',
    'order_complete_thank_you': 'Order complete. Thank your for your order.',
    'please_select_address': 'Address is required.',
    'please_select_payment_option': 'Please select your payment option.',
    
    'ok': 'OK',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'alert': 'Alert',
    
    'order': 'Order',
    'address': 'Address',
    'setting': 'Setting',
    'manage_shop': 'Manage Shop',
    'open_shop': 'Open Shop',
    'log_out': 'Log Out',
    
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'add_a_new_address': 'Add a New Address',
    'create_address': 'Create Address',
    'edit_address': 'Edit Address',
    'province': 'Province',
    'district': 'District',
    'postcode': 'Postcode',
    'telephone': 'Telephone',
    'set_as_default': 'Set as Default',
    'account_setting': 'Account Setting',
    'current_password': 'Current Password',
    'change_password': 'Change Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'create_your_shop': 'Create Your Shop',
    'create_shop': 'Create Shop',
    'shop_name': 'Shop Name',
    'shop_url': 'Url',

    'credit_or_debit_card': 'Credit or Debit Card',
    'cash_on_delivery': 'Cash on Delivery',
    'bank_transfer': 'Bank Transfer',
    'prepare_shipment': 'Prepare Shipment',
    'no_item_in_cart': 'There are no items in this cart.',

    'title_signup_complete': 'Thank you for siging up',
    'title_please_login': 'Please login',

    'msg_internal_error': 'An error occurred',
    'msg_signup_complete': 'We have sent an email with an activation link to your email address. To complete sign up, please click the activation link.',
    'msg_name_is_required': 'Name is required.',
    'msg_email_is_required': 'Email is required.',
    'msg_invalid_email_format': 'Invalid email format.',
    'msg_password_is_required': 'Password is required.',
    'msg_password_must_be_6': 'Password must be at least 6 characters long.',
    'msg_password_not_match': 'Password not match.',
    'msg_min_6_char': 'Minimum 6 characters length.',
    'msg_save_success': 'Your data has been successfully saved.',
    'msg_update_success': 'Your data has been successfully updated.',
    'msg_item_add_to_cart': 'You added {0} item(s) to cart.',
    'msg_address_is_required': 'Address is required.',
    'msg_province_is_required': 'Province is required.',
    'msg_district_is_required': 'District is required.',
    'msg_postcode_is_required': 'Postcode is required.',
    'msg_telephone_is_required': 'Telephone is required.',
    
    'success': 'Success',
    'information': 'Information',
    'error': 'Error'
};