export const LANG_TH_TRANS = {
    'home': 'หน้าหลัก',
    'login': 'เข้าสู่ระบบ',
    'thailand_post_full_name': 'บริษัท ไปรษณีย์ไทย จำกัด',
    'search_for_products': 'ค้นหาสินค้า...',
    'search_results_for': 'ผลการค้นหาคำว่า',
    'all': 'ทั้งหมด',

    'product_category': 'หมวดหมู่สินค้า',
    'new_products': 'สินค้ามาใหม่',
    'best_seller': 'สินค้าขายดี',

    'sub_category': 'หมวดหมู่สินค้า',

    'results_for': 'ผลการค้นหาคำว่า',
    'no_result': 'ไม่พบรายการ',
    'related_category': 'หมวดหมู่สินค้า',
    'items': 'รายการ',

    'login_to': 'เข้าสู่ระบบ',
    'full_name': 'ชื่อ - นามสกุล',
    'email': 'อีเมล',
    'password': 'รหัสผ่าน',
    'confirm_password': 'ยืนยันรหัสผ่าน',
    'not_a_member': 'ยังไม่ได้เป็นสมาชิก?',
    'sign_up_now': 'สมัครเลย',
    'create_account': 'สร้างบัญชีผู้ใช้งาน',
    'create_a_new_account': 'สร้างบัญชีผู้ใช้งานใหม่',
    'confirm_payment': 'แจ้งชำระเงิน',

    'description': 'คำอธิบาย',
    'add_to_cart': 'เพิ่มไปยังรถเข็น',
    'buy_now': 'ซื้อทันที',
    'tracking_no': 'หมายเลขพัสดุ',
    'paid': 'ชำระเงินแล้ว',
    'unpaid': 'ยังไม่ชำระเงิน',

    'cart': 'สินค้าในรถเข็น',
    'delivery_address': 'ที่อยู่สำหรับจัดส่ง',
    'payment': 'ชำระเงิน',
    'payment_option': 'วิธีชำระเงิน',
    'complete': 'จบขั้นตอน',
    'product': 'สินค้า',
    'price': 'ราคา',
    'quantity': 'จำนวน',
    'qty': 'จำนวน',
    'total': 'รวม',
    'total_summary': 'ยอดรวมทั้งหมด',
    'select_address': 'เลือกที่อยู่',
    'choose_payment_option': 'เลือกวิธีชำระเงิน',
    'order_summary': 'สรุปรายการสั่งซื้อ',
    'place_order': 'ยืนยันคำสั่งซื้อ',
    'order_no': 'เลขที่รายการสั่งซื้อ',
    'order_detail': 'รายละเอียดรายการสั่งซื้อ',
    'order_date': 'วันที่',
    'order_status': 'สถานะ',
    'order_short_info': 'สรุปยอด',
    'order_complete_thank_you': 'ทำการสั่งซื้อเสร็จสมบูรณ์',
    'please_select_address': 'กรุณาระบุที่อยู่',
    'please_select_payment_option': 'กรุณาเลือกวิธีชำระเงิน',
    'msg_address_is_required': 'กรุณาระบุที่อยู่',
    'msg_province_is_required': 'กรุณาเลือกจังหวัด',
    'msg_district_is_required': 'กรุณาเลือกอำเภอ',
    'msg_postcode_is_required': 'กรุณาเลือกรหัสไปรษณีย์',
    'msg_telephone_is_required': 'กรุณาระบุเบอร์โทรศัพท์',
    'msg_credit_card_rejected': 'บัตรของคุณถูกปฏิเสธ ไม่สามารถทำการชำระเงินได้',
    'msg_amount_is_required': 'กรุณาระบุยอดโอน',

    'loading': 'กำลังโหลดข้อมูล...',
    'loading_logging_in': 'กำลังเข้าสู่ระบบ...',

    'ok': 'ตกลง',
    'cancel': 'ยกเลิก',
    'confirm': 'ยืนยัน',
    'alert': 'แจ้งเตือน',
    'close': 'ปิด',

    'order': 'รายการสั่งซื้อ',
    'address': 'ที่อยู่',
    'setting': 'แก้ไขข้อมูล',
    'manage_shop': 'จัดการร้าน',
    'open_shop': 'เปิดร้าน',
    'log_out': 'ออกจากระบบ',

    'save': 'บันทึก',
    'edit': 'แก้ไข',
    'delete': 'ลบ',
    'add_a_new_address': 'เพิ่มที่อยู่ใหม่',
    'create_address': 'เพิ่มที่อยู่',
    'edit_address': 'แก้ไขที่อยู่',
    'province': 'จังหวัด',
    'district': 'อำเภอ',
    'postcode': 'รหัสไปรษณีย์',
    'telephone': 'โทรศัพท์',
    'set_as_default': 'ตั้งเป็นค่าเริ่มต้น',    
    'account_setting': 'แก้ไขข้อมูลส่วนตัว',
    'current_password': 'รหัสผ่านเดิม',
    'change_password': 'เปลี่ยนรหัสผ่าน',
    'new_password': 'รหัสผ่านใหม่',
    'confirm_new_password': 'ยืนยันรหัสผ่านใหม่',
    'create_your_shop': 'สร้างร้าน',
    'create_shop': 'สร้างร้าน',
    'shop_name': 'ชื่อร้าน',
    'shop_url': 'Url',
    'bank_name': 'ธนาคาร',
    'account_no': 'เลขที่บัญชี',
    'account_name': 'ชื่อบัญชี',
    'transfer_amount': 'ยอดโอน',
    'transfer_date': 'วันที่โอน',
    'time': 'เวลา',
    'transfer_file': 'หลักฐานการโอน',
    'save_this_address': 'บันทึกที่อยู่นี้สำหรับใช้ในต่อไป',
    'bank_info_and_payment': 'ข้อมูลธนาคาร / แจ้งชำระเงิน',
    
    'credit_or_debit_card': 'บัตรเครดิตหรือบัตรเดบิต',
    'cash_on_delivery': 'เก็บเงินปลายทาง',
    'bank_transfer': 'โอนเงินผ่านบัญชีธนาคาร',
    'prepare_shipment': 'เตรียมการฝากส่ง',    
    'no_item_in_cart': 'ไม่มีรายการสินค้าในรถเข็น',

    'title_signup_complete': 'ขอบคุณสำหรับการลงทะเบียน',
    'title_please_login': 'กรุณาเข้าสู่ระบบ',

    'msg_internal_error': 'เกิดข้อผิดพลาด',    
    'msg_signup_complete': 'ระบบได้ทำการส่ง link ยืนยันตัวตนสำหรับการลงทะเบียนไปยังอีเมลของคุณแล้ว เพื่อให้การลงทะเบียนเสร็จสมบูรณ์กรุณาคลิก link ในอีเมลของคุณ',
    'msg_name_is_required': 'กรุณาระบุชื่อ',
    'msg_email_is_required': 'กรุณาระบุอีเมล',
    'msg_invalid_email_format': 'รูปแบบอีเมลไม่ถูกต้อง',
    'msg_password_is_required': 'กรุณาระบุรหัสผ่าน',
    'msg_password_must_be_6': 'รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร',
    'msg_password_not_match': 'รหัสผ่านไม่ตรงกัน',
    'msg_min_6_char': 'ความยาวอย่างน้อย 6 ตัวอักษร',
    'msg_save_success': 'บันทึกข้อมูลเสร็จสมบูรณ์',
    'msg_update_success': 'แก้ไขข้อมูลเสร็จสมบูรณ์',
    'msg_item_add_to_cart': 'คุณได้ทำการเพิ่มสินค้าจำนวน {0} ชิ้นลงในรถเข็น',
    'msg_order_is_required': 'กรุณาระบุคำสั่งซื้อ',

    'success': 'สำเร็จ',
    'information': 'ข้อมูล',
    'error': 'เกิดข้อผิดพลาด'
};